export default {
  DESIGN_KIT: '/designKit',
  LOGIN: '/designKit/login',
  SHARED: '/designKit/shared',
  LOADING: '/designKit/loading',
  ACCOUNT: '/designKit/account',
  ERROR_CSV: '/designKit/errorCsv',
  SMALLMODAL: '/designKit/smallModal',
  COMPONENTS: '/designKit/components',
  LAYOUT_USER: '/designKit/layoutUser',
  SEARCH_PAGE: '/designKit/searchPage',
  EMAILSEARCH: '/designKit/emailSearch',
  EMAILTHREAD: '/designKit/emailThread',
  SEARCH_EMPTY: '/designKit/searchEmpty',
  SUCCESS_DIALOG: '/designKit/successDialog',
  LAYOUT_USERDETAIL: '/designKit/layoutUserDetail',
  ORGANIZATION_SETUP: '/designKit/organizationSetup',
  ORGANIZATION_PROGRESS: '/designKit/organizationProgress',
};
