export const httpConstants = {
  invitationHeader: 'invitation-token',
  authorizationHeader: 'Authorization',
  statusCode: {
    SUCCESS: 200,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    NOT_FOUND: 404,
    FORBIDDEN: 403,
    METHOD_NOT_ALLOWED: 405,
    REQUEST_TIMEOUT: 408,
    SERVER_ERROR: 500,
  },
  responseType: {
    CONTINUE: 'Continue',
    OK: 'OK',
    ACCEPTED: 'Accepted',
    NO_CONTENT: 'No Content',
    NOT_MODIFIED: 'Not Modified',
    PERMANENT_REDIRECT: 'Permanent Redirect',
    BAD_REQUEST: 'Bad Request',
    UN_AUTHORIZED: 'Un-authorized',
    NOT_FOUND: 'Not Found',
    METHOD_NOT_ALLOWED: 'Method Not Allowed',
    REQUEST_TIMEOUT: 'Request Timeout',
    CONFLICT: 'Conflict',
    INTERNAL_SERVER_ERROR: 'Internal Server Error',
    NOT_IMPLEMENTED: 'Not Implemented',
    BAD_GATEWAY: 'Bad Gateway',
    SERVICE_UNAVAILABLE: 'Service Unavailable',
  },
  requestMethods: {
    POST: 'post',
    GET: 'get',
    DELETE: 'delete',
    PUT: 'put',
  },
};
