export default {
  ROOT: '/',
  DESIGN_KIT: '/designKit',
  USER_MANAGEMENT: '/userManagement',
  USER_DETAILS: '/users/:id',
  PAGE_NOT_FOUND: '/*',
  SEARCH: '/search',
  USAGE: '/user-usage',
  ACCOUNT: '/account',
  USERS: '/users',
  LOGIN: '/login',
  SIGN_UP: '/signup',
  COMPANY_ADMIN_DOMAIN_UPLOAD: '/onboarding/domain-upload',
  COMPANY_ADMIN_WAITING_PAGE: '/onboarding/awaiting',
  ORGANIZATION_SETUP: '/onboarding/organizationSetup',
  COMPANY_ADMIN_ENVIRONMENT: '/onboarding/environment-setup',
  VERIFY_EMAIL: '/verify-email/:schemaName/:tokenId',
  ON_BOARDING: '/onboarding',
  EMAIL_ACTIVITY: '/email-activity/:id',
  ACCOUNT_SETTINGS: '/account/settings',
  ACCOUNT_PROFILE: '/account/profile',
  ACCOUNT_LOGOUT: '/account/logout',
  SUPER_ADMIN_LOGIN: '/super-admin-login',
  SUPER_ADMIN_CLIENT: '/super-admin/client',
  SUPER_ADMIN_CLIENT_DETAILS: '/super-admin/client/:id',
  SUPER_ADMIN_ACCOUNT: '/super-admin/account',
};
